"""Updated  Users table

Revision ID: 69ae638ef59f
Revises: 58ffdee054fa
Create Date: 2026-07-20 20:59:55.174590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ae638ef59f'
down_revision: Union[str, Sequence[str], None] = '58ffdee054fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.execute("UPDATE users SET username = 'unknown' WHERE username IS NULL")
    op.alter_column('users', 'username', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
