"""Added new tasks table for groups features

Revision ID: a017e3ebbc32
Revises: e6f1a89c10d2
Create Date: 2026-07-28 18:25:29.564957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a017e3ebbc32'
down_revision: Union[str, Sequence[str], None] = 'e6f1a89c10d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type first before altering column
    role_enum = postgresql.ENUM('member', 'admin', 'owner', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('group_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_tasks_id'), 'group_tasks', ['id'], unique=False)
    op.alter_column('GroupMembers', 'role',
               existing_type=sa.VARCHAR(),
               type_=role_enum,
               existing_nullable=False,
               postgresql_using='role::role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('GroupMembers', 'role',
               existing_type=postgresql.ENUM('member', 'admin', 'owner', name='role'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_group_tasks_id'), table_name='group_tasks')
    op.drop_table('group_tasks')
    role_enum = postgresql.ENUM('member', 'admin', 'owner', name='role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
