"""Relationship are added 

Revision ID: c20dee064caf
Revises: 69ae638ef59f
Create Date: 2026-07-22 17:53:19.836222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20dee064caf'
down_revision: Union[str, Sequence[str], None] = '69ae638ef59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('users_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'Tasks', 'users', ['users_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tasks', type_='foreignkey')
    op.drop_column('Tasks', 'users_id')
    # ### end Alembic commands ###
